# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            pacman -Syu --force --noconfirm
tagline:          pelmers
url:              http://blog.pelmers.com
paginate:         1
baseurl:          /
author:
  name:           Peter Elmers
  url:            https://github.com/pelmers
  email:          peter.elmers@yahoo.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/pelmers
pages_list:
  About: '/about'
  Feed: '/atom.xml'
